[project]
name = "data-prep"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopandas>=1.1.2",
    "jupyterlab>=4.5.1",
    "pandas>=2.3.3",
    "rich>=14.2.0",
]
